<a href="https://colab.research.google.com/github/jonathanastudillo-lab/Ejercicio/blob/main/House_Prices_Advanced_Regression_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

primero se cargan las librerías

SSL para cargar desde internet un archivo
pandas para empezar a trabajar en la base de datos

In [11]:
import ssl
import pandas as pd
import numpy as np


ssl._create_default_https_context = ssl._create_unverified_context
# Usamos la URL raw para obtener solo el contenido del CSV
url = "https://raw.githubusercontent.com/jonathanastudillo-lab/Ejercicio/main/train_houseprice.csv"
df = pd.read_csv(url)
print(df.shape)
df.head()

(1460, 81)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

la base tiene 1460 filas y 81 columnas

2) tratamiento de datos

2.1 estadística descriptiva

In [12]:
# 1) Ver tamaño y primeras filas
print("Dimensión del DataFrame:", df.shape)
display(df.head())

# 2) Separar variables numéricas y categóricas
num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = df.select_dtypes(exclude=[np.number]).columns.tolist()

print("Cantidad de variables numéricas:", len(num_cols))
print("Cantidad de variables categóricas:", len(cat_cols))

print("\nVariables numéricas:")
print(num_cols)

print("\nVariables categóricas:")
print(cat_cols)

# 3) Resumen estadístico de variables numéricas
resumen_numerico = df[num_cols].describe().T
display(resumen_numerico)

# 4) Función para winsorizar entre percentil 1 y percentil 99
def winsorize_p1_p99(df, cols):
    df_out = df.copy()
    bounds = {}

    for c in cols:
        p1 = df_out[c].quantile(0.01)
        p99 = df_out[c].quantile(0.99)
        bounds[c] = (p1, p99)
        df_out[c] = df_out[c].clip(lower=p1, upper=p99)

    return df_out, bounds

Dimensión del DataFrame: (1460, 81)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

Cantidad de variables numéricas: 38
Cantidad de variables categóricas: 43

Variables numéricas:
['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SalePrice']

Variables categóricas:
['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition']

,count,mean,std,min,25%,50%,75%,max
Id,1460.0,730.500000,421.610009,1.0,365.75,730.5,1095.25,1460.0
MSSubClass,1460.0,56.897260,42.300571,20.0,20.00,50.0,70.00,190.0
LotFrontage,1201.0,70.049958,24.284752,21.0,59.00,69.0,80.00,313.0
LotArea,1460.0,10516.828082,9981.264932,1300.0,7553.50,9478.5,11601.50,215245.0
OverallQual,1460.0,6.099315,1.382997,1.0,5.00,6.0,7.00,10.0
OverallCond,1460.0,5.575342,1.112799,1.0,5.00,5.0,6.00,9.0
YearBuilt,1460.0,1971.267808,30.202904,1872.0,1954.00,1973.0,2000.00,2010.0
YearRemodAdd,1460.0,1984.865753,20.645407,1950.0,1967.00,1994.0,2004.00,2010.0
MasVnrArea,1452.0,103.685262,181.066207,0.0,0.00,0.0,166.00,1600.0
BsmtFinSF1,1460.0,443.639726,456.098091,0.0,0.00,383.5,712.25,5644.0
BsmtFinSF2,1460.0,46.549315,161.319273,0.0,0.00,0.0,0.00,1474.0
BsmtUnfSF,1460.0,567.240411,441.866955,0.0,223.00,477.5,808.00,2336.0
TotalBsmtSF,1460.0,1057.429452,438.705324,0.0,795.75,991.5,1298.25,6110.0
1stFlrSF,1460.0,1162.626712,386.587738,334.0,882.00,1087.0,1391.25,4692.0
2ndFlrSF,1460.0,346.992466,436.528436,0.0,0.00,0.0,728.00,2065.0
LowQualFinSF,1460.0,5.844521,48.623081,0.0,0.00,0.0,0.00,572.0
GrLivArea,1460.0,1515.463699,525.480383,334.0,1129.50,1464.0,1776.75,5642.0
BsmtFullBath,1460.0,0.425342,0.518911,0.0,0.00,0.0,1.00,3.0
BsmtHalfBath,1460.0,0.057534,0.238753,0.0,0.00,0.0,0.00,2.0
FullBath,1460.0,1.565068,0.550916,0.0,1.00,2.0,2.00,3.0
HalfBath,1460.0,0.382877,0.502885,0.0,0.00,0.0,1.00,2.0
BedroomAbvGr,1460.0,2.866438,0.815778,0.0,2.00,3.0,3.00,8.0
KitchenAbvGr,1460.0,1.046575,0.220338,0.0,1.00,1.0,1.00,3.0
TotRmsAbvGrd,1460.0,6.517808,1.625393,2.0,5.00,6.0,7.00,14.0
Fireplaces,1460.0,0.613014,0.644666,0.0,0.00,1.0,1.00,3.0
GarageYrBlt,1379.0,1978.506164,24.689725,1900.0,1961.00,1980.0,2002.00,2010.0
GarageCars,1460.0,1.767123,0.747315,0.0,1.00,2.0,2.00,4.0
GarageArea,1460.0,472.980137,213.804841,0.0,334.50,480.0,576.00,1418.0
WoodDeckSF,1460.0,94.244521,125.338794,0.0,0.00,0.0,168.00,857.0
OpenPorchSF,1460.0,46.660274,66.256028,0.0,0.00,25.0,68.00,547.0
EnclosedPorch,1460.0,21.954110,61.119149,0.0,0.00,0.0,0.00,552.0
3SsnPorch,1460.0,3.409589,29.317331,0.0,0.00,0.0,0.00,508.0
ScreenPorch,1460.0,15.060959,55.757415,0.0,0.00,0.0,0.00,480.0
PoolArea,1460.0,2.758904,40.177307,0.0,0.00,0.0,0.00,738.0
MiscVal,1460.0,43.489041,496.123024,0.0,0.00,0.0,0.00,15500.0
MoSold,1460.0,6.321918,2.703626,1.0,5.00,6.0,8.00,12.0
YrSold,1460.0,2007.815753,1.328095,2006.0,2007.00,2008.0,2009.00,2010.0
SalePrice,1460.0,180921.195890,79442.502883,34900.0,129975.00,163000.0,214000.00,755000.0

en la varaibles categóricas no tiene sentido hacer análisis:

'MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition'

In [14]:
# 5) Aplicar winsorización solo a variables numéricas
df_w, bounds = winsorize_p1_p99(df, num_cols)

# 6) Convertir bounds a tabla para verlo ordenado
bounds_df = pd.DataFrame(bounds, index=["p1", "p99"]).T
bounds_df.index.name = "Variable"

print("\nPercentiles usados para winsorización:")
display(bounds_df)

# 7) Comparación simple antes y después
print("Resumen ANTES de winsorizar:")
display(df[num_cols].describe().T)

print("Resumen DESPUÉS de winsorizar:")
display(df_w[num_cols].describe().T)

Percentiles usados para winsorización:

                     p1        p99
Variable
Id                15.59    1445.41
MSSubClass        20.00     190.00
LotFrontage       21.00     141.00
LotArea         1680.00   37567.64
OverallQual        3.00      10.00
OverallCond        3.00       9.00
YearBuilt       1899.18    2009.00
YearRemodAdd    1950.00    2009.00
MasVnrArea         0.00     791.92
BsmtFinSF1         0.00    1572.41
BsmtFinSF2         0.00     830.38
BsmtUnfSF          0.00    1797.05
TotalBsmtSF        0.00    2155.05
1stFlrSF         520.00    2219.46
2ndFlrSF           0.00    1418.92
LowQualFinSF       0.00     360.00
GrLivArea        692.18    3123.48
BsmtFullBath       0.00       2.00
BsmtHalfBath       0.00       1.00
FullBath           1.00       3.00
HalfBath           0.00       1.00
BedroomAbvGr       1.00       5.00
KitchenAbvGr       1.00       2.00
TotRmsAbvGrd       3.00      11.00
Fireplaces         0.00       2.00
GarageYrBlt     1916.00    2009.00
GarageCars         0.00       3.00
GarageArea         0.00    1002.79
WoodDeckSF         0.00     505.46
OpenPorchSF        0.00     285.82
EnclosedPorch      0.00     261.05
3SsnPorch          0.00     168.00
ScreenPorch        0.00     268.05
PoolArea           0.00       0.00
MiscVal            0.00     700.00
MoSold             1.00      12.00
YrSold          2006.00    2010.00
SalePrice      61815.97  442567.01

Resumen ANTES de winsorizar:

,count,mean,std,min,25%,50%,75%,max
Id,1460.0,730.500000,421.610009,1.0,365.75,730.5,1095.25,1460.0
MSSubClass,1460.0,56.897260,42.300571,20.0,20.00,50.0,70.00,190.0
LotFrontage,1201.0,70.049958,24.284752,21.0,59.00,69.0,80.00,313.0
LotArea,1460.0,10516.828082,9981.264932,1300.0,7553.50,9478.5,11601.50,215245.0
OverallQual,1460.0,6.099315,1.382997,1.0,5.00,6.0,7.00,10.0
OverallCond,1460.0,5.575342,1.112799,1.0,5.00,5.0,6.00,9.0
YearBuilt,1460.0,1971.267808,30.202904,1872.0,1954.00,1973.0,2000.00,2010.0
YearRemodAdd,1460.0,1984.865753,20.645407,1950.0,1967.00,1994.0,2004.00,2010.0
MasVnrArea,1452.0,103.685262,181.066207,0.0,0.00,0.0,166.00,1600.0
BsmtFinSF1,1460.0,443.639726,456.098091,0.0,0.00,383.5,712.25,5644.0
BsmtFinSF2,1460.0,46.549315,161.319273,0.0,0.00,0.0,0.00,1474.0
BsmtUnfSF,1460.0,567.240411,441.866955,0.0,223.00,477.5,808.00,2336.0
TotalBsmtSF,1460.0,1057.429452,438.705324,0.0,795.75,991.5,1298.25,6110.0
1stFlrSF,1460.0,1162.626712,386.587738,334.0,882.00,1087.0,1391.25,4692.0
2ndFlrSF,1460.0,346.992466,436.528436,0.0,0.00,0.0,728.00,2065.0
LowQualFinSF,1460.0,5.844521,48.623081,0.0,0.00,0.0,0.00,572.0
GrLivArea,1460.0,1515.463699,525.480383,334.0,1129.50,1464.0,1776.75,5642.0
BsmtFullBath,1460.0,0.425342,0.518911,0.0,0.00,0.0,1.00,3.0
BsmtHalfBath,1460.0,0.057534,0.238753,0.0,0.00,0.0,0.00,2.0
FullBath,1460.0,1.565068,0.550916,0.0,1.00,2.0,2.00,3.0
HalfBath,1460.0,0.382877,0.502885,0.0,0.00,0.0,1.00,2.0
BedroomAbvGr,1460.0,2.866438,0.815778,0.0,2.00,3.0,3.00,8.0
KitchenAbvGr,1460.0,1.046575,0.220338,0.0,1.00,1.0,1.00,3.0
TotRmsAbvGrd,1460.0,6.517808,1.625393,2.0,5.00,6.0,7.00,14.0
Fireplaces,1460.0,0.613014,0.644666,0.0,0.00,1.0,1.00,3.0
GarageYrBlt,1379.0,1978.506164,24.689725,1900.0,1961.00,1980.0,2002.00,2010.0
GarageCars,1460.0,1.767123,0.747315,0.0,1.00,2.0,2.00,4.0
GarageArea,1460.0,472.980137,213.804841,0.0,334.50,480.0,576.00,1418.0
WoodDeckSF,1460.0,94.244521,125.338794,0.0,0.00,0.0,168.00,857.0
OpenPorchSF,1460.0,46.660274,66.256028,0.0,0.00,25.0,68.00,547.0
EnclosedPorch,1460.0,21.954110,61.119149,0.0,0.00,0.0,0.00,552.0
3SsnPorch,1460.0,3.409589,29.317331,0.0,0.00,0.0,0.00,508.0
ScreenPorch,1460.0,15.060959,55.757415,0.0,0.00,0.0,0.00,480.0
PoolArea,1460.0,2.758904,40.177307,0.0,0.00,0.0,0.00,738.0
MiscVal,1460.0,43.489041,496.123024,0.0,0.00,0.0,0.00,15500.0
MoSold,1460.0,6.321918,2.703626,1.0,5.00,6.0,8.00,12.0
YrSold,1460.0,2007.815753,1.328095,2006.0,2007.00,2008.0,2009.00,2010.0
SalePrice,1460.0,180921.195890,79442.502883,34900.0,129975.00,163000.0,214000.00,755000.0

Resumen DESPUÉS de winsorizar:

,count,mean,std,min,25%,50%,75%,max
Id,1460.0,730.500000,421.343430,15.59,365.75,730.5,1095.25,1445.41
MSSubClass,1460.0,56.897260,42.300571,20.00,20.00,50.0,70.00,190.00
LotFrontage,1201.0,69.600333,21.723531,21.00,59.00,69.0,80.00,141.00
LotArea,1460.0,10063.006575,5062.299090,1680.00,7553.50,9478.5,11601.50,37567.64
OverallQual,1460.0,6.104110,1.369444,3.00,5.00,6.0,7.00,10.00
OverallCond,1460.0,5.580137,1.098826,3.00,5.00,5.0,6.00,9.00
YearBuilt,1460.0,1971.413493,29.806332,1899.18,1954.00,1973.0,2000.00,2009.00
YearRemodAdd,1460.0,1984.861644,20.640499,1950.00,1967.00,1994.0,2004.00,2009.00
MasVnrArea,1452.0,101.174793,168.046772,0.00,0.00,0.0,166.00,791.92
BsmtFinSF1,1460.0,438.530240,429.049203,0.00,0.00,383.5,712.25,1572.41
BsmtFinSF2,1460.0,44.404589,148.265347,0.00,0.00,0.0,0.00,830.38
BsmtUnfSF,1460.0,565.397089,436.085086,0.00,223.00,477.5,808.00,1797.05
TotalBsmtSF,1460.0,1050.610788,404.387881,0.00,795.75,991.5,1298.25,2155.05
1stFlrSF,1460.0,1158.294452,363.802701,520.00,882.00,1087.0,1391.25,2219.46
2ndFlrSF,1460.0,345.021781,430.816964,0.00,0.00,0.0,728.00,1418.92
LowQualFinSF,1460.0,4.893151,39.450730,0.00,0.00,0.0,0.00,360.00
GrLivArea,1460.0,1510.289658,495.148927,692.18,1129.50,1464.0,1776.75,3123.48
BsmtFullBath,1460.0,0.424658,0.516163,0.00,0.00,0.0,1.00,2.00
BsmtHalfBath,1460.0,0.056164,0.230318,0.00,0.00,0.0,0.00,1.00
FullBath,1460.0,1.571233,0.538823,1.00,1.00,2.0,2.00,3.00
HalfBath,1460.0,0.374658,0.484200,0.00,0.00,0.0,1.00,1.00
BedroomAbvGr,1460.0,2.863699,0.778338,1.00,2.00,3.0,3.00,5.00
KitchenAbvGr,1460.0,1.045890,0.209319,1.00,1.00,1.0,1.00,2.00
TotRmsAbvGrd,1460.0,6.508904,1.592667,3.00,5.00,6.0,7.00,11.00
Fireplaces,1460.0,0.609589,0.634547,0.00,0.00,1.0,1.00,2.00
GarageYrBlt,1379.0,1978.546048,24.572216,1916.00,1961.00,1980.0,2002.00,2009.00
GarageCars,1460.0,1.763699,0.739318,0.00,1.00,2.0,2.00,3.00
GarageArea,1460.0,471.460856,208.996193,0.00,334.50,480.0,576.00,1002.79
WoodDeckSF,1460.0,93.155411,120.812804,0.00,0.00,0.0,168.00,505.46
OpenPorchSF,1460.0,45.825548,61.985174,0.00,0.00,25.0,68.00,285.82
EnclosedPorch,1460.0,21.434760,58.382129,0.00,0.00,0.0,0.00,261.05
3SsnPorch,1460.0,2.520548,19.932690,0.00,0.00,0.0,0.00,168.00
ScreenPorch,1460.0,14.326541,51.369279,0.00,0.00,0.0,0.00,268.05
PoolArea,1460.0,0.000000,0.000000,0.00,0.00,0.0,0.00,0.00
MiscVal,1460.0,19.482192,104.884363,0.00,0.00,0.0,0.00,700.00
MoSold,1460.0,6.321918,2.703626,1.00,5.00,6.0,8.00,12.00
YrSold,1460.0,2007.815753,1.328095,2006.00,2007.00,2008.0,2009.00,2010.00
SalePrice,1460.0,179926.416233,74052.658892,61815.97,129975.00,163000.0,214000.00,442567.01

Se identificaron las variables numéricas y categóricas de la base House Prices.

 Luego, para reducir el efecto de valores extremos, se aplicó winsorización a las variables numéricas, reemplazando los valores inferiores al percentil 1 y superiores al percentil 99 por esos límites.

Ahora veremos una variable puntual "SALES"

para ver como quedó antes y después

In [19]:
print("variable Sale")
bounds_df.loc["SalePrice"]

variable Sale

p1      61815.97
p99    442567.01
Name: SalePrice, dtype: float64

In [18]:


print("Antes:")
print(df["SalePrice"].describe())

print("\nDespués:")
print(df_w["SalePrice"].describe())

Antes:
count      1460.000000
mean     180921.195890
std       79442.502883
min       34900.000000
25%      129975.000000
50%      163000.000000
75%      214000.000000
max      755000.000000
Name: SalePrice, dtype: float64

Después:
count      1460.000000
mean     179926.416233
std       74052.658892
min       61815.970000
25%      129975.000000
50%      163000.000000
75%      214000.000000
max      442567.010000
Name: SalePrice, dtype: float64

Ahora revisamos y tratamos los missing value

In [21]:
# Conteo de missing
missing_count = df_w.isna().sum().sort_values(ascending=False)
missing_pct = (df_w.isna().mean() * 100).sort_values(ascending=False)

pd.DataFrame({"missing_count": missing_count, "missing_pct": missing_pct}).head(20)

              missing_count  missing_pct
PoolQC                 1453    99.520548
MiscFeature            1406    96.301370
Alley                  1369    93.767123
Fence                  1179    80.753425
MasVnrType              872    59.726027
FireplaceQu             690    47.260274
LotFrontage             259    17.739726
GarageQual               81     5.547945
GarageFinish             81     5.547945
GarageType               81     5.547945
GarageYrBlt              81     5.547945
GarageCond               81     5.547945
BsmtFinType2             38     2.602740
BsmtExposure             38     2.602740
BsmtCond                 37     2.534247
BsmtQual                 37     2.534247
BsmtFinType1             37     2.534247
MasVnrArea                8     0.547945
Electrical                1     0.068493
Condition2                0     0.000000

las variables PoolQC MiscFeature Alley Fence MasVnrType FireplaceQu se considerarán variables que tienen mas del 20% de sus valores como missing value

lo interpretaremos como que varias de esas variables faltan porque la característica no existe en esa casa, por ejemplo:

PoolQC → si no tiene piscina

Alley → si no tiene callejón de acceso

Fence → si no tiene cerco

FireplaceQu → si no tiene chimenea

GarageQual, GarageType, etc. → si no tiene garaje

BsmtExposure, BsmtCond, etc. → si no tiene sótano

O sea, aquí el missing muchas veces significa **No existe** y no simplemente **faltó registrar**

In [22]:
import pandas as pd
import numpy as np

# Copia de trabajo
df_clean = df_w.copy()

# 1) Eliminar columnas con exceso extremo de missing
drop_cols = ["PoolQC", "MiscFeature", "Alley", "Fence"]
drop_cols = [c for c in drop_cols if c in df_clean.columns]
df_clean.drop(columns=drop_cols, inplace=True)

# 2) Categóricas donde el NA significa "no existe esa característica"
fill_none_cols = [
    "MasVnrType",
    "FireplaceQu",
    "GarageType", "GarageFinish", "GarageQual", "GarageCond",
    "BsmtQual", "BsmtCond", "BsmtExposure", "BsmtFinType1", "BsmtFinType2"
]

for c in fill_none_cols:
    if c in df_clean.columns:
        df_clean[c] = df_clean[c].fillna("None")

# 3) Numéricas donde el NA también representa ausencia real
fill_zero_cols = [
    "MasVnrArea",
    "BsmtFinSF1", "BsmtFinSF2", "BsmtUnfSF", "TotalBsmtSF",
    "BsmtFullBath", "BsmtHalfBath",
    "GarageCars", "GarageArea", "GarageYrBlt"
]

for c in fill_zero_cols:
    if c in df_clean.columns:
        df_clean[c] = df_clean[c].fillna(0)

# 4) LotFrontage: imputar con la mediana por Neighborhood
if "LotFrontage" in df_clean.columns and "Neighborhood" in df_clean.columns:
    df_clean["LotFrontage"] = df_clean.groupby("Neighborhood")["LotFrontage"].transform(
        lambda x: x.fillna(x.median())
    )
    # por si algún barrio quedara completo en NA
    df_clean["LotFrontage"] = df_clean["LotFrontage"].fillna(df_clean["LotFrontage"].median())

# 5) Variables categóricas restantes: imputar con la moda
cat_cols_clean = df_clean.select_dtypes(exclude=[np.number]).columns.tolist()
for c in cat_cols_clean:
    if df_clean[c].isna().sum() > 0:
        df_clean[c] = df_clean[c].fillna(df_clean[c].mode()[0])

# 6) Variables numéricas restantes: imputar con la mediana
num_cols_clean = df_clean.select_dtypes(include=[np.number]).columns.tolist()
for c in num_cols_clean:
    if df_clean[c].isna().sum() > 0:
        df_clean[c] = df_clean[c].fillna(df_clean[c].median())

# 7) Verificación final
missing_final = df_clean.isna().sum().sort_values(ascending=False)
print(missing_final.head(20))
print("\nTotal de missing restantes:", df_clean.isna().sum().sum())
print("\nDimensión final:", df_clean.shape)

Id              0
MSSubClass      0
MSZoning        0
LotFrontage     0
LotArea         0
Street          0
LotShape        0
LandContour     0
Utilities       0
LotConfig       0
LandSlope       0
Neighborhood    0
Condition1      0
Condition2      0
BldgType        0
HouseStyle      0
OverallQual     0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
dtype: int64

Total de missing restantes: 0

Dimensión final: (1460, 77)

En la base House Prices, los valores faltantes se trataron de forma diferenciada según su significado. Se eliminaron variables con exceso extremo de missing, se imputó “None” en variables categóricas donde la ausencia representa que la vivienda no posee dicha característica, se imputó 0 en variables numéricas asociadas a ausencia real, y en el resto se utilizaron medidas robustas como la mediana o la moda.

--------------
ahora veremos si existe alguna correlación entrevariables, porque  en muchos modelos, sobre todo los lineales, meter dos variables muy correlacionadas puede:

meter ruido innecesario

dificultar la interpretación

generar multicolinealidad

hacer el modelo menos limpio

Ejemplo simple:

GarageCars = cantidad de autos en garaje

GarageArea = tamaño del garaje

Probablemente estén bastante correlacionadas, porque a más autos, normalmente más área

Entonces a veces conviene dejar solo una

In [ ]:
# Recalcular columnas numéricas desde df_clean
num_cols_clean = df_clean.select_dtypes(include=[np.number]).columns.tolist()

# Matriz de correlación
corr = df_clean[num_cols_clean].corr(method="pearson")

# Ver matriz completa
display(corr)

# Ver correlaciones más fuertes entre variables (sin repetir pares)
corr_abs = corr.abs()
upper = corr_abs.where(np.triu(np.ones(corr_abs.shape), k=1).astype(bool))

top_pairs = upper.stack().sort_values(ascending=False)
display(top_pairs.head(20))